name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: "home-assistant/actions/hassfest@master"
        name: HassFest

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Package integration into zip
        run: |
          cd ${{ github.workspace }}/custom_components/bticino_intercom
          zip -r ${{ github.workspace }}/bticino_intercom-${{ env.VERSION }}.zip . -x ".*" -x "__pycache__/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            ${{ github.workspace }}/bticino_intercom-${{ env.VERSION }}.zip
